global:
  projectName: ruby
  env: dev

imageTag: "f43c03e"

## Pod HealthCheck
readinessProbe:
  path: /healthcheck
  initialDelaySeconds: 20
livenessProbe:
  path: /healthcheck
  initialDelaySeconds: 20

## If you want to enable HPA
k8sObjectsEnabled:
  hpa: false ## Disabled HPA in Dev env to save cost, enabled QA --> Prod

replicaCount: 1

#+++++++++++++++++++++++++++++++++Developer Use++++++++++++++++++++++++++++++++++#
configMap:
  data:
    non-sensitive-key: "non-sensitive-value"