global:
  projectName: ruby
  env: dev

imageTag: "073dfb9"

## Pod HealthCheck
readinessProbe:
  path: /healthcheck
  initialDelaySeconds: 20
livenessProbe:
  path: /healthcheck
  initialDelaySeconds: 20

## If you want to enable HPA
k8sObjectsEnabled:
  hpa: false ## Disabled HPA in Dev env which can be used for development only and can save cost, enabled HPA in [QA --> Prod]

replicaCount: 1

#+++++++++++++++++++++++++++++++++Developer Use++++++++++++++++++++++++++++++++++#
configMap:
  data:
    non-sensitive-key: "non-sensitive-value"