apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ruby-app-dev
  namespace: argocd
spec:
  project: ruby-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: ruby-dev
  sources:
    - repoURL: https://github.com/maitymondeep/ruby-app
      path: infrastructure/helm-chart
      targetRevision: develop
      helm:
        valueFiles:
          - values.yaml
          - $values/infrastructure/helm-values/environments/dev/dev-values.yaml
    - repoURL: 'https://github.com/maitymondeep/ruby-app'
      targetRevision: HEAD
      ref: values
