apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: ruby-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  sources:
    - repoURL: https://github.com/maitymondeep/ruby-app
      path: infrastructure/observability/grafana
      targetRevision: develop
      helm:
        valueFiles:
          - values.yaml

