global:
  projectName: ruby
  env: prod

imageTag: ""

## Pod HealthCheck
readinessProbe:
  path: /healthcheck
  initialDelaySeconds: 20
livenessProbe:
  path: /healthcheck
  initialDelaySeconds: 20

## If you want to enable HPA
k8sObjectsEnabled:
  hpa: true
autoscaling:
  minReplicas: 3
  maxReplicas: 6

#+++++++++++++++++++++++++++++++++Developer Use++++++++++++++++++++++++++++++++++#
configMap:
  data:
    non-sensitive-key: "non-sensitive-value"
